### ISSUE TITLE
option to ignore specials

### ISSUE THREAD

**Issue by liam8888999** [bossanova808/script.service.checkpreviousepisode#7]
some shows are hard to get specials (e.g. S00E01) is it possible to add an option to ignore special episodes completely and only function on season 1 and above

**Comment by bossanova808** [comment]
Hmm, I've never noticed it tripping on a special, and wouldn't think it would.

Can you post a **full debug log** of it doing so, please?

**Comment by bossanova808** [comment]
Going to close this as no response.
